[package]
name = "jsonprops"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.21"
fern = "0.6.2"
serde_json = "1.0.117"
anyhow = "1.0.83"
clap = { version = "4.5.4", features = ["derive"] }
humantime = "2.1.0"
